name: PathDiffuser
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - aom=3.9.1
  - attr=2.5.2
  - backports.zstd=1.3.0
  - blas=2.108
  - blas-devel=3.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cpython=3.11.14
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=8.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.5
  - glslang=16.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - level-zero=1.28.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.25
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.2
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libuuid=2.41.3
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.1
  - pango=1.56.4
  - pcre2=10.47
  - pip=26.0.1
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pyg=2.6.1
  - pysocks=1.7.1
  - python=3.11.11
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cluster=1.6.3
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.4.0
  - setuptools=80.10.2
  - shaderc=2025.5
  - snappy=1.2.2
  - spirv-tools=2026.1
  - svt-av1=4.0.1
  - tbb=2022.3.0
  - tk=8.6.13
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.46.3
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - yaml=0.2.5
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - absl-py==2.1.0
      - accelerate==0.17.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - anndata==0.11.3
      - argcomplete==3.5.3
      - array-api-compat==1.11
      - asttokens==3.0.0
      - attrs==25.1.0
      - av==14.2.0
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - clean-fid==0.1.35
      - click==8.1.8
      - cmake==3.25.0
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cssselect2==0.8.0
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dependency-groups==1.3.0
      - diffusers==0.17.1
      - distlib==0.3.9
      - docker-pycreds==0.4.0
      - executing==2.2.0
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - h5py==3.13.0
      - huggingface-hub==0.29.1
      - idna==3.4
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - inflect==6.0.4
      - ipykernel==6.29.5
      - ipython==9.0.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - legacy-api-wrap==1.4.1
      - lightning-bolts==0.7.0
      - lightning-utilities==0.12.0
      - lit==15.0.7
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - multidict==6.1.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nox==2025.2.9
      - numba==0.61.0
      - numpy==1.24.4
      - nvidia-ml-py==12.575.51
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.4
      - pastel==0.2.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - poethepoet==0.10.0
      - polars==1.23.0
      - pot==0.9.5
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==1.10.9
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.5
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - regex==2024.11.6
      - requests==2.28.1
      - rich==13.9.4
      - safetensors==0.5.3
      - scanpy==1.11.0
      - scikit-learn==1.2.2
      - scipy==1.15.2
      - scprep==1.2.3
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - session-info2==0.1.2
      - setproctitle==1.3.5
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - tomlkit==0.13.2
      - torchcde==0.2.5
      - torchcfm==1.0.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.6.1
      - torchsde==0.2.6
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.30.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - umap-learn==0.5.7
      - universal-pathlib==0.2.6
      - urllib3==1.26.13
      - virtualenv==20.29.2
      - wandb==0.18.7
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
      - zipp==3.21.0
